const data = [
    {
        id: 1,
        jobTitle: 'AI/ML Developer',
        experience: '5-10 years',
        location: 'Delhi, Bangalore',
        jobType: 'Full Time',
        driveDate: '01/06/2025',
        skills: ['Python','SQL','Backend'],
        logo: "https://img.icons8.com/ios/50/amazon.png",
    },
    {
        id: 2,
        jobTitle: 'AI/ML Architect',
        experience: '5-10 years',
        location: 'Delhi, Bangalore',
        jobType: 'Full Time',
        driveDate: '01/06/2025',
        skills: ['Python','SQL','Backend'],
        logo: "https://img.icons8.com/ios/50/amazon.png",
    },
    {
        id: 3,
        jobTitle: 'Fullstack Developer',
        experience: '5-10 years',
        location: 'Delhi, Bangalore',
        jobType: 'Full Time',
        driveDate: '01/06/2025',
        skills: ['Python','SQL','Backend'],
        logo: "https://img.icons8.com/ios/50/amazon.png",
    },
    {
        id: 4,
        jobTitle: 'Data Scientist',
        experience: '5-10 years',
        location: 'Delhi, Bangalore',
        jobType: 'Full Time',
        driveDate: '01/06/2025',
        skills: ['Python','SQL','Backend'],
        logo: "https://img.icons8.com/ios/50/amazon.png",
    },
    {
        id: 5,
        jobTitle: 'AI/ML Developer',
        experience: '5-10 years',
        location: 'Delhi, Bangalore',
        jobType: 'Full Time',
        driveDate: '01/06/2025',
        skills: ['Python','SQL','Backend'],
        logo: "https://img.icons8.com/ios/50/amazon.png",
    },
    {
        id: 6,
        jobTitle: 'AI/ML Developer',
        experience: '5-10 years',
        location: 'Delhi, Bangalore',
        jobType: 'Full Time',
        driveDate: '01/06/2025',
        skills: ['Python','SQL','Backend'],
        logo: "https://img.icons8.com/ios/50/amazon.png",
    },
    {
        id: 7,
        jobTitle: 'AI/ML Developer',
        experience: '5-10 years',
        location: 'Delhi, Bangalore',
        jobType: 'Full Time',
        driveDate: '01/06/2025',
        skills: ['Python','SQL','Backend'],
        logo: "https://img.icons8.com/ios/50/amazon.png",
    }
];

export default data;